import localFont from 'next/font/local';
import './globals.css';
import Header from './components/Header';
import { ThemeProvider } from 'next-themes';
import { ClerkProvider } from '@clerk/nextjs';
import Footer from './components/Footer';
import Sidebar from './components/sidebar';  // <-- Include the Sidebar here

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // Optionally, use logic to conditionally render Sidebar based on the current path
  const isDashboard = false; // Add your logic to detect if it's the dashboard or any page you want to exclude the Sidebar

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning
        >
          {/* ThemeProvider from next-themes for shadcn/ui compatibility */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="bg-white text-black dark:bg-black dark:text-white min-h-screen">
              <Header />
              <div className="flex">
                {/* Conditionally render Sidebar */}
                {!isDashboard && (
                  <div className="md:w-100">
                    <Sidebar />
                  </div>
                )}

                <main className="w-full">{children}</main>
              </div>
              {/* <Footer /> */}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
