'use client';
import localFont from 'next/font/local';
import './globals.css';
import Header from './components/Header';
import { ThemeProvider } from 'next-themes';
import { ClerkProvider } from '@clerk/nextjs';
import Footer from './components/Footer';
import Sidebar from './components/Sidebar';  // Default Sidebar
import { usePathname } from 'next/navigation';  // Use this for route checking

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  // Use pathname to detect if on the dashboard
  const pathname = usePathname();
  const isDashboard = pathname.includes('dashboard'); // Check if the current path contains 'dashboard'

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning
        >
          {/* ThemeProvider for shadcn/ui compatibility */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="bg-white text-black dark:bg-black dark:text-white min-h-screen">
              <Header />
              <div className="flex">
                {/* Conditionally render Sidebar based on whether we're on the dashboard */}
                {!isDashboard && (
                  <div className="md:w-100">
                    <Sidebar />
                  </div>
                )}

                {/* Main content area */}
                <main className="w-full">{children}</main>
              </div>
              {/* <Footer /> */}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
